name: Main

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
      - run: npm i
      - run: npm run lint
      # - run: npm run test
      # - run: npm run ghp
      # push changes to the docs automatically
